M48
; DRILL file {KiCad (6.0.2)} date Mon 07 Mar 2022 08:12:57 PM CST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-07T20:12:57-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0197
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
%
G90
G05
T1
X4.715Y-3.105
X5.1Y-3.365
X5.1Y-3.465
X5.34Y-3.47
T2
X4.965Y-3.13
X4.965Y-3.23
T3
X4.77Y-3.205
X4.77Y-3.305
X4.77Y-3.405
T0
M30
